# deps_ncnn.cmake
# Handle ncnn dependency: either use a system-installed ncnn or build the
# bundled ncnn submodule (inspired by LiteOCR and wan-ncnn-vulkan).

option(USE_SYSTEM_NCNN "Build with system libncnn" OFF)

if(USE_SYSTEM_NCNN)
    find_package(Threads)
    find_package(SPIRV-Tools QUIET)
    find_package(SPIRV-Tools-opt QUIET)
    find_package(glslang QUIET)

    if(glslang_FOUND)
        if(NOT TARGET glslang AND TARGET glslang::glslang)
            add_library(glslang ALIAS glslang::glslang)
        endif()
        if(NOT TARGET SPIRV AND TARGET glslang::SPIRV)
            add_library(SPIRV ALIAS glslang::SPIRV)
        endif()
    else()
        set(GLSLANG_TARGET_DIR "GLSLANG-NOTFOUND" CACHE PATH "Absolute path to glslangTargets.cmake directory")
        if(NOT GLSLANG_TARGET_DIR AND NOT DEFINED ENV{GLSLANG_TARGET_DIR})
            message(WARNING "set glslang_DIR to glslang-config.cmake directory for using system glslang.")
            message(WARNING "GLSLANG_TARGET_DIR must be defined! USE_SYSTEM_NCNN will be turned off.")
            set(USE_SYSTEM_NCNN OFF)
        else()
            include("${GLSLANG_TARGET_DIR}/OSDependentTargets.cmake" OPTIONAL)
            include("${GLSLANG_TARGET_DIR}/OGLCompilerTargets.cmake" OPTIONAL)
            if(EXISTS "${GLSLANG_TARGET_DIR}/HLSLTargets.cmake")
                include("${GLSLANG_TARGET_DIR}/HLSLTargets.cmake")
            endif()
            include("${GLSLANG_TARGET_DIR}/glslangTargets.cmake" OPTIONAL)
            include("${GLSLANG_TARGET_DIR}/SPIRVTargets.cmake" OPTIONAL)
        endif()
    endif()

    if(TARGET glslang AND TARGET SPIRV)
        get_property(glslang_location TARGET glslang PROPERTY LOCATION)
        get_property(SPIRV_location TARGET SPIRV PROPERTY LOCATION)
        message(STATUS "Found glslang: ${glslang_location}")
        message(STATUS "Found SPIRV: ${SPIRV_location}")
    else()
        if(NCNN_LLM_ENABLE_VULKAN)
            message(WARNING "NCNN_LLM_ENABLE_VULKAN=ON requires glslang/SPIRV, but they were not found. USE_SYSTEM_NCNN will be turned off.")
        else()
            message(WARNING "glslang or SPIRV target not found! USE_SYSTEM_NCNN will be turned off.")
        endif()
        set(USE_SYSTEM_NCNN OFF)
    endif()
endif()

if(USE_SYSTEM_NCNN)
    find_package(ncnn)
    if(NOT TARGET ncnn)
        message(WARNING "ncnn target not found! USE_SYSTEM_NCNN will be turned off.")
        set(USE_SYSTEM_NCNN OFF)
    elseif(NCNN_LLM_ENABLE_VULKAN)
        get_target_property(_ncnn_iface_defs ncnn INTERFACE_COMPILE_DEFINITIONS)
        set(_ncnn_has_vulkan OFF)
        if(_ncnn_iface_defs)
            foreach(_def ${_ncnn_iface_defs})
                if(_def STREQUAL "NCNN_VULKAN")
                    set(_ncnn_has_vulkan ON)
                endif()
            endforeach()
        endif()
        if(NOT _ncnn_has_vulkan)
            message(WARNING "NCNN_LLM_ENABLE_VULKAN=ON but system ncnn does not appear to be built with Vulkan. Falling back to bundled ncnn.")
            set(USE_SYSTEM_NCNN OFF)
        endif()
    endif()
endif()

if(NOT USE_SYSTEM_NCNN)
    if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/ncnn/CMakeLists.txt")
        message(FATAL_ERROR
            "The ncnn submodule was not downloaded! "
            "Please update submodules with \"git submodule update --init --recursive\" and try again.")
    endif()

    set(NCNN_INSTALL_SDK OFF CACHE BOOL "" FORCE)
    set(NCNN_BUILD_BENCHMARK OFF CACHE BOOL "" FORCE)
    set(NCNN_BUILD_TESTS OFF CACHE BOOL "" FORCE)
    # ncnn's own tools (ncnnoptimize / ncnnllm2int / ...) are normally not needed at runtime.
    # Set -DNCNN_LLM_ENABLE_TOOLS=ON to build them into build_cmake/ncnn/tools/Release.
    if(NCNN_LLM_ENABLE_TOOLS)
        set(NCNN_BUILD_TOOLS ON CACHE BOOL "" FORCE)
    else()
        set(NCNN_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
    endif()
    set(NCNN_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(NCNN_VULKAN ${NCNN_LLM_ENABLE_VULKAN} CACHE BOOL "" FORCE)
    set(NCNN_SYSTEM_GLSLANG OFF CACHE BOOL "" FORCE)
    set(NCNN_SHARED_LIB OFF CACHE BOOL "" FORCE)
    set(GLSLANG_ENABLE_INSTALL OFF CACHE BOOL "" FORCE)
    set(NCNN_STDIO ON CACHE BOOL "" FORCE)
    set(NCNN_SIMPLESTL OFF CACHE BOOL "" FORCE)
    set(NCNN_BUILD_WITH_STATIC_CRT OFF CACHE BOOL "" FORCE)

    add_subdirectory(ncnn)
endif()
